//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSRSim3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAttachment
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public byte[] Attachment { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
